Ols = {
	ITEM_TYPE_DISCUSSION: 'discussion',
	ITEM_TYPE_ISSUE: 'issue',
	ITEM_TYPE_ARTICLE: 'article',

	ISSUE_TYPE_BUG: 'bug',
	ISSUE_TYPE_TASK: 'task',
	ISSUE_TYPE_ENHANCEMENT: 'enhancement',

	MSG_TYPE_CHAT: 'MSG_TYPE_CHAT',
	MSG_TYPE_ITEM: 'MSG_TYPE_ITEM',

	MESSAGE_AGE_HOURS_INCREMENT: 1,
	FILL_SCREEN_MSG_COUNT: 30,
	MESSAGE_PAGE_SIZE: 20,

	ROLE_ADMIN: 'ADMIN',
	ROLE_USER: 'USER'
}
