Ols = { //FIXME: Move all of these into more appropriate locations within the API

	//--- START MOVED: These have been moved to Ols.Item
	ITEM_TYPE_DISCUSSION: 'discussion',
	ITEM_TYPE_ISSUE: 'issue',
	ITEM_TYPE_ARTICLE: 'article',

	ISSUE_TYPE_BUG: 'bug',
	ISSUE_TYPE_TASK: 'task',
	ISSUE_TYPE_ENHANCEMENT: 'enhancement',
	//---- END MOVED

	//--- START MOVED: These have been moved to Ols.Message
	MSG_TYPE_CHAT: 'MSG_TYPE_CHAT',
	MSG_TYPE_ACTIVITY: 'MSG_TYPE_ACTIVITY',
	//---- END MOVED

	ACTIVITY_TYPE_NEW_BOARD: 'ACTIVITY_TYPE_NEW_BOARD',
	ACTIVITY_TYPE_NEW_ITEM: 'ACTIVITY_TYPE_NEW_ITEM',
	ACTIVITY_TYPE_ITEM_TYPE_CHANGE: 'ACTIVITY_TYPE_ITEM_TYPE_CHANGE',
	ACTIVITY_TYPE_ITEM_OPENED: 'ACTIVITY_TYPE_ITEM_OPENED',
	ACTIVITY_TYPE_ITEM_CLOSED: 'ACTIVITY_TYPE_ITEM_CLOSED',
	ACTIVITY_TYPE_ITEM_MOVED_TO: 'ACTIVITY_TYPE_ITEM_MOVED_TO',
	ACTIVITY_TYPE_ITEM_MOVED_FROM: 'ACTIVITY_TYPE_ITEM_MOVED_FROM',
	ACTIVITY_TYPE_ITEM_TITLE_CHANGED: 'ACTIVITY_TYPE_ITEM_TITLE_CHANGED',
	ACTIVITY_TYPE_ITEM_DESC_CHANGED: 'ACTIVITY_TYPE_ITEM_DESC_CHANGED',

	MESSAGE_AGE_HOURS_INCREMENT: 1,
	FILL_SCREEN_MSG_COUNT: 10,
	MESSAGE_PAGE_SIZE: 10,

	ROLE_ADMIN: 'ADMIN',
	ROLE_USER: 'USER'
}
